export const LEVELS = [
  {
    id: 1,
    title: 'Locality 1',
    interval: 'Double tempo',
    cueType: 'tempo-slide',
    zoneCount: 2,
    laneLabels: ['Top', 'Bottom'],
    baseTempo: 120,
    ratio: 2,
    helpText: 'Listen to the tempo slide. If it speeds up, go to Top. If it slows down, go to Bottom.',
    description: 'Tempo slides between a base tempo and its double.',
  },
  {
    id: 2,
    title: 'Locality 2',
    interval: '1.5 tempo',
    cueType: 'tempo-slide',
    zoneCount: 2,
    laneLabels: ['Top', 'Bottom'],
    baseTempo: 120,
    ratio: 1.5,
    helpText: 'Listen to the tempo slide. If it speeds up, go to Top. If it slows down, go to Bottom.',
    description: 'Tempo slides between a base tempo and 1.5x of that tempo.',
  },
  {
    id: 3,
    title: 'Locality 3',
    interval: 'Two tempos',
    cueType: 'tempo-pair',
    zoneCount: 2,
    laneLabels: ['Top', 'Bottom'],
    baseTempo: 120,
    ratio: 2,
    cueByLaneTempoRatios: {
      0: [1, 2],
      1: [2, 1],
    },
    modeCueTimings: {
      nibble: { firstStartBeatsBeforeImpact: 12, secondStartBeatsAfterFirst: 4 },
      bite: { firstStartBeatsBeforeImpact: 10, secondStartBeatsAfterFirst: 4 },
      gobble: { firstStartBeatsBeforeImpact: 6, secondStartBeatsAfterFirst: 2 },
      devour: { firstStartBeatsBeforeImpact: 4, secondStartBeatsAfterFirst: 2 },
    },
    helpText: 'Hear two tempos in sequence. Base then double means Top. Double then base means Bottom.',
    description: 'Two steady tempos played back-to-back.',
  },
  {
    id: 4,
    title: 'Locality 4',
    interval: 'Double or half',
    cueType: 'tempo-pair',
    zoneCount: 2,
    laneLabels: ['Top', 'Bottom'],
    baseTempo: 120,
    ratio: 2,
    cueByLaneTempoRatios: {
      0: [1, 2],
      1: [1, 0.5],
    },
    modeCueTimings: {
      nibble: { firstStartBeatsBeforeImpact: 12, secondStartBeatsAfterFirst: 4 },
      bite: { firstStartBeatsBeforeImpact: 10, secondStartBeatsAfterFirst: 4 },
      gobble: { firstStartBeatsBeforeImpact: 6, secondStartBeatsAfterFirst: 2 },
      devour: { firstStartBeatsBeforeImpact: 4, secondStartBeatsAfterFirst: 2 },
    },
    helpText: 'Both cues start at base tempo. Double means Top. Half tempo means Bottom.',
    description: 'Base tempo followed by either double or half tempo.',
  },
  {
    id: 5,
    title: 'Locality 5',
    interval: 'Three over two or four',
    cueType: 'tempo-pair',
    zoneCount: 2,
    laneLabels: ['Top', 'Bottom'],
    baseTempo: 120,
    cueByLaneTempoRatios: {
      0: [1, 1.5],
      1: [1, 0.75],
    },
    modeCueTimings: {
      nibble: { firstStartBeatsBeforeImpact: 12, secondStartBeatsAfterFirst: 4 },
      bite: { firstStartBeatsBeforeImpact: 10, secondStartBeatsAfterFirst: 2 },
      gobble: { firstStartBeatsBeforeImpact: 8, secondStartBeatsAfterFirst: 4 },
      devour: {
        firstStartBeatsBeforeImpact: 6,
        secondStartBeatsAfterFirst: 2,
        obstacleSpacingBeats: 6,
      },
    },
    helpText: 'Both cues start at base tempo. Three-in-two means Top. Three-in-four means Bottom.',
    description: 'Base tempo followed by either 3/2 or 3/4 tempo.',
  },
  {
    id: 6,
    title: 'Locality 6',
    interval: 'Three tempos',
    cueType: 'tempo-pair',
    zoneCount: 3,
    laneLabels: ['Top', 'Middle', 'Bottom'],
    baseTempo: 120,
    ratio: 2,
    cueByLaneTempoRatios: {
      0: [1, 2],
      1: [1, 1],
      2: [1, 0.5],
    },
    modeCueTimings: {
      nibble: { firstStartBeatsBeforeImpact: 12, secondStartBeatsAfterFirst: 4 },
      bite: { firstStartBeatsBeforeImpact: 10, secondStartBeatsAfterFirst: 4 },
      gobble: { firstStartBeatsBeforeImpact: 6, secondStartBeatsAfterFirst: 2 },
      devour: { firstStartBeatsBeforeImpact: 4, secondStartBeatsAfterFirst: 2 },
    },
    helpText: 'Hear the tempo. Fast (double) means Top. Steady (regular) means Middle. Slow (half) means Bottom.',
    description: 'Three zones: double tempo, regular tempo, and half tempo.',
  },
];
