import { styles as globalStyles } from '../../styles';
import { ROW_H, GRAPH_H } from './constants';

export const S = {
  section: { border: '2px dashed #111', marginBottom: 0 },
  banner: { background: '#F5F2EB', padding: '14px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 },
  bannerText: { ...globalStyles.sectionTitle, fontSize: 24, color: '#111' },
  bannerSub: { fontSize: 14, color: '#333', lineHeight: 1.45, marginTop: 4, fontFamily: 'var(--font-space-mono), monospace' },
  inner: { padding: '20px 20px 24px', background: '#F5C842' },
  tabsRow: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 12, flexWrap: 'wrap' },
  tabs: { display: 'flex', border: '2.5px solid #111', width: 'fit-content' },
  tab: (active) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', padding: '9px 20px', cursor: 'pointer', background: active ? '#E8473F' : '#fff', color: active ? '#EEE8D0' : '#111', border: 'none', borderRight: '2.5px solid #111' }),
  tabLast: (active) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', padding: '9px 20px', cursor: 'pointer', background: active ? '#E8473F' : '#fff', color: active ? '#EEE8D0' : '#111', border: 'none' }),
  hintsToggle: { display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', userSelect: 'none' },
  hintsLabel: { fontSize: 10, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', color: '#111' },
  helpButton: (open) => ({ width: 28, height: 28, borderRadius: '50%', border: '2px solid #111', background: open ? '#E8473F' : '#fff', color: open ? '#EEE8D0' : '#111', fontFamily: 'var(--font-space-mono), monospace', fontSize: 15, fontWeight: 900, cursor: 'pointer', lineHeight: 1 }),
  toggleTrack: (on) => ({ width: 36, height: 20, background: on ? '#E8473F' : '#fff', border: '2px solid #111', position: 'relative', transition: 'background 0.15s', flexShrink: 0 }),
  toggleThumb: (on) => ({ position: 'absolute', top: 1, left: on ? 17 : 1, width: 14, height: 14, background: on ? '#EEE8D0' : '#F5C842', border: '1.5px solid #111', transition: 'left 0.15s' }),
  instructions: { fontSize: 14, color: '#222', fontFamily: 'var(--font-space-mono), monospace', lineHeight: 1.45, textAlign: 'center', marginBottom: 14 },
  directionWord: { fontWeight: 900, textTransform: 'uppercase' },
  soundUnlockOverlay: { position: 'absolute', zIndex: 4, inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(245, 242, 235, 0.72)' },
  soundUnlockBtn: { fontFamily: 'var(--font-space-mono), monospace', fontSize: 12, fontWeight: 900, letterSpacing: 1.2, textTransform: 'uppercase', padding: '12px 18px', border: '2.5px solid #111', cursor: 'pointer', background: '#E8473F', color: '#EEE8D0', boxShadow: '4px 4px 0 #111' },
  graphOuter: { border: '2.5px solid #111', background: '#F5F2EB', marginBottom: 8, position: 'relative' },
  graphInner: { display: 'flex' },
  yAxis: { width: 40, flexShrink: 0, borderRight: '2px solid #111', display: 'flex', flexDirection: 'column', background: '#EDEAE0', height: GRAPH_H },
  yCell: { display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 9, fontWeight: 700, color: '#444', fontFamily: 'var(--font-space-mono), monospace', borderBottom: '1px solid #D5D1C5', height: ROW_H, flexShrink: 0, userSelect: 'none' },
  yCellSa: { display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 9, fontWeight: 900, color: '#E8473F', fontFamily: 'var(--font-space-mono), monospace', borderBottom: '1px solid #D5D1C5', height: ROW_H, flexShrink: 0, userSelect: 'none' },
  canvasWrap: { flex: 1, overflow: 'hidden', position: 'relative', touchAction: 'none' },
  canvas: { display: 'block', width: '100%', height: GRAPH_H },
  xAxis: { display: 'flex', marginLeft: 40, borderTop: '2px solid #111', background: '#EDEAE0' },
  xCell: { flex: 1, textAlign: 'center', fontSize: 9, fontWeight: 700, color: '#444', fontFamily: 'var(--font-space-mono), monospace', borderRight: '1px solid #D5D1C5', display: 'flex', alignItems: 'center', justifyContent: 'center', height: 28, minWidth: 0, userSelect: 'none' },
  controls: { display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', marginTop: 4 },
  goalBtn: (playing) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', padding: '10px 15px', border: playing ? '2px solid #E8473F' : '2px solid #111', cursor: 'pointer', background: playing ? '#E8473F' : '#111', color: '#fff', whiteSpace: 'nowrap' }),
  mineBtn: (playing) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', padding: '10px 15px', border: playing ? '2px solid #E8473F' : '2px solid #111', cursor: 'pointer', background: playing ? '#E8473F' : '#fff', color: playing ? '#fff' : '#111', whiteSpace: 'nowrap' }),
  gbtn: { fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', padding: '10px 15px', border: '2px solid #111', cursor: 'pointer', background: '#fff', color: '#111', whiteSpace: 'nowrap' },
  checkBtn: (active) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', padding: '10px 15px', border: '2px solid #111', cursor: 'pointer', background: active ? '#4CAF76' : '#fff', color: active ? '#fff' : '#111', whiteSpace: 'nowrap' }),
  nextBtn: { fontFamily: 'var(--font-space-mono), monospace', fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', padding: '10px 15px', border: '2px solid #111', cursor: 'pointer', background: '#111', color: '#fff', whiteSpace: 'nowrap' },
  gameStatus: { fontSize: 13, color: '#222', fontFamily: 'var(--font-space-mono), monospace', fontWeight: 700, lineHeight: 1.45, letterSpacing: 0.5, textAlign: 'center', width: '100%', marginTop: 6 },
  helpOverlay: { position: 'absolute', zIndex: 5, inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 10, background: 'rgba(245, 242, 235, 0.88)' },
  helpPanel: { width: 'min(640px, 100%)', border: '2.5px solid #111', background: '#F5C842', boxShadow: '5px 5px 0 #111', padding: 10 },
  helpHead: { display: 'grid', gridTemplateColumns: '26px 1fr 26px', alignItems: 'center', gap: 12, marginBottom: 8 },
  helpTitle: { fontFamily: 'var(--font-bebas-neue), sans-serif', fontSize: 22, letterSpacing: 1.5, color: '#111', textAlign: 'center' },
  helpClose: { width: 26, height: 26, border: '2px solid #111', background: '#fff', color: '#111', fontFamily: 'var(--font-space-mono), monospace', fontWeight: 900, cursor: 'pointer' },
  helpTabs: { display: 'flex', border: '2.5px solid #111', width: 'fit-content', margin: '0 auto 8px' },
  helpTab: (active) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 9, fontWeight: 700, letterSpacing: 1.4, textTransform: 'uppercase', padding: '6px 14px', cursor: 'pointer', background: active ? '#E8473F' : '#fff', color: active ? '#EEE8D0' : '#111', border: 'none', borderRight: '2px solid #111' }),
  helpTabLast: (active) => ({ fontFamily: 'var(--font-space-mono), monospace', fontSize: 9, fontWeight: 700, letterSpacing: 1.4, textTransform: 'uppercase', padding: '6px 14px', cursor: 'pointer', background: active ? '#E8473F' : '#fff', color: active ? '#EEE8D0' : '#111', border: 'none' }),
  helpBody: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  helpCard: { border: '2px solid #111', background: '#F5F2EB', padding: 8, minHeight: 148 },
  helpCardTitle: { fontFamily: 'var(--font-space-mono), monospace', fontSize: 10, fontWeight: 900, letterSpacing: 1.3, textTransform: 'uppercase', marginBottom: 6, color: '#111' },
  helpGrid: { position: 'relative', height: 112, border: '2px solid #111', background: '#fff', overflow: 'hidden' },
  helpBlock: (beat, row, beats, extra = {}) => ({
    position: 'absolute',
    left: `${beat * 25}%`,
    top: row,
    width: `${beats * 25}%`,
    height: 26,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid #111',
    background: '#F5C842',
    color: '#111',
    fontFamily: 'var(--font-space-mono), monospace',
    fontSize: 10,
    fontWeight: 900,
    boxSizing: 'border-box',
    ...extra,
  }),
  helpTick: { position: 'absolute', right: 7, bottom: 7, width: 26, height: 26, borderRadius: '50%', border: '2px solid #111', background: '#E8473F', color: '#EEE8D0', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 900, opacity: 0 },
};
