export const CATEGORIES = [
  {
    id: 'voice',
    title: 'Free Your Voice',
    shortDesc: 'Use your voice like it was meant to be used — an extension of you in the world.',
    styles: ['Khayaal', 'Dhrupad', 'Pop', 'Rock', 'Bollywood'],
    subcategories: [
      { id: 'vocal-strain', title: 'Overcoming vocal strain', desc: 'Free yourself from tension — and sing without effort, strain or fatigue.' },
      { id: 'singing-technique', title: 'Healthy singing technique', desc: 'Build a voice grounded in breath, resonance and ease.' },
      { id: 'singing-intention', title: 'Singing intention', desc: 'Develop precision in pitch, vowel colour and dynamic expression.' },
    ],
  },
  {
    id: 'instrument',
    title: 'Speak Through Your Instrument',
    shortDesc: 'Make your instrument an inalienable part of you — like another voice.',
    subcategories: [
      { id: 'electric-guitar', title: 'Electric guitar', desc: 'From clean tones to distortion — find your voice on the electric.' },
      { id: 'acoustic-guitar', title: 'Acoustic guitar', desc: 'Fingerpicking, strumming, songwriting — the acoustic as a complete instrument.' },
      { id: 'classical-guitar', title: 'Classical guitar', desc: 'Nylon string technique, classical repertoire and expressive finesse.' },
      { id: 'bass-guitar', title: 'Bass guitar', desc: 'Lock into the groove and become the foundation of any band.' },
      { id: 'fretless-guitar', title: 'Fretless guitar', desc: 'Microtones, glides and the voice-like quality of the fretless.' },
      { id: 'ukulele', title: 'Ukulele', desc: 'The joyful, portable instrument — great for beginners and songwriters.' },
      { id: 'flute', title: 'Flute', desc: "Breath, tone and expression on one of the world's oldest instruments." },
      { id: 'violin', title: 'Violin', desc: 'Bowing technique, tone production and melodic vocabulary on the violin.' },
      { id: 'cello', title: 'Cello', desc: 'The most voice-like of string instruments — rich, warm and expressive.' },
      { id: 'viola', title: 'Viola', desc: 'The middle voice of the string family, with its own unique character.' },
      { id: 'piano', title: 'Piano', desc: 'Keys, harmony and the instrument that holds it all together.' },
      { id: 'melodica', title: 'Melodica', desc: 'The playful keyboard instrument that breathes like a wind instrument.' },
      { id: 'rudra-veena', title: 'Rudra veena', desc: "One of India's ancient, meditative string instruments." },
      { id: 'drums', title: 'Drums', desc: 'Time, groove and the art of holding the rhythm together.' },
      { id: 'swarmandal', title: 'Swarmandal', desc: 'The harp-like drone instrument of Indian classical music.' },
    ],
  },
  {
    id: 'rhythm',
    title: 'Unlock Rhythm',
    shortDesc: 'Understand the foundation of every performing art: time.',
    subcategories: [
      { id: 'konnakol', title: 'Konnakol', desc: 'The ancient South Indian art of vocal percussion — rhythm through syllables.' },
      { id: 'rhythm-drums', title: 'Drums', desc: 'Time, groove and the art of holding the rhythm together.' },
      { id: 'body-percussion', title: 'Body percussion', desc: 'Use your own body as a rhythm instrument — claps, stomps and more.' },
      { id: 'rap', title: 'Application to rap', desc: 'Apply rhythmic thinking to flow, delivery and lyrical timing.' },
      { id: 'song-lyrics', title: 'Application to song lyrics', desc: 'Find the rhythmic pulse within melody and lyrics.' },
    ],
  },
  {
    id: 'poetry',
    title: 'Express With Poetry',
    shortDesc: 'Learn how sound and meaning can combine to bring your music to life.',
    subcategories: [
      { id: 'english-lyrics', title: 'English lyrics', desc: 'Write songs that mean something — craft, imagery and musicality.' },
      { id: 'hindi-lyrics', title: 'Hindi lyrics', desc: 'Explore the rich tradition of Hindi songwriting and poetry.' },
      { id: 'english-poetry', title: 'English poetry', desc: 'From free verse to form — find your voice on the page.' },
      { id: 'theory-of-poetry', title: 'Theory of poetry', desc: 'Metre, rhyme, prosody — the underlying structure of poetic language.' },
    ],
  },
  {
    id: 'music',
    title: 'Understand Music',
    shortDesc: "Understand and respond to musical thoughts like you're speaking a language.",
    subcategories: [
      { id: 'ear-training', title: 'Ear training', desc: "Hear what's happening in music — and be able to name and reproduce it." },
      { id: 'music-theory', title: 'Music theory', desc: 'Understand the grammar of music — scales, chords and harmony.' },
      { id: 'composition', title: 'Composition', desc: 'Create original music with intention and structural understanding.' },
      { id: 'improvisation', title: 'Improvisation', desc: 'Respond spontaneously and musically in any context.' },
      { id: 'sight-reading', title: 'Sight reading', desc: 'Read and play music at first sight — fluently and confidently.' },
    ],
  },
];
