const STYLES = ['Khayaal', 'Dhrupad', 'Pop', 'Rock', 'Bollywood', 'Rap', 'Other'];

export const CATEGORIES = [
  {
    id: 'voice',
    title: 'Free Your Voice',
    filterTitle: 'Voice',
    shortDesc: 'Use your voice like it was meant to be used — an extension of you in the world.',
    styles: STYLES,
    subcategories: [
      { id: 'intention-voice', title: 'Intention and Voice' },
      { id: 'vocal-strain', title: 'Overcoming Vocal Strain' },
    ],
  },
  {
    id: 'instrument',
    title: 'Speak Through Your Instrument',
    filterTitle: 'Instrument',
    shortDesc: 'Make your instrument an inalienable part of you — like another voice.',
    styles: STYLES,
    subcategories: [
      { id: 'voice', title: 'Voice' },
      { id: 'electric-guitar', title: 'Electric Guitar' },
      { id: 'acoustic-guitar', title: 'Acoustic Guitar' },
      { id: 'classical-guitar', title: 'Classical Guitar' },
      { id: 'bass-guitar', title: 'Bass Guitar' },
      { id: 'fretless-guitar', title: 'Fretless Guitar' },
      { id: 'bansuri', title: 'Bansuri (Indian Flute)' },
      { id: 'cello', title: 'Cello' },
      { id: 'piano', title: 'Piano' },
      { id: 'melodica', title: 'Melodica' },
      { id: 'drums', title: 'Drums' },
      { id: 'swarmandal', title: 'Swarmandal (Indian Harp)' },
    ],
  },
  {
    id: 'rhythm',
    title: 'Unlock Rhythm',
    filterTitle: 'Rhythm',
    shortDesc: 'Understand the foundation of every performing art: time.',
    styles: STYLES,
    subcategories: [
      { id: 'rhythmic-intuition', title: 'Rhythmic Intuition' },
      { id: 'rap', title: 'Applying Rhythm to Rap' },
      { id: 'song-lyrics', title: 'Applying Rhythm to Songs' },
    ],
  },
  {
    id: 'poetry',
    title: 'Express With Poetry',
    filterTitle: 'Poetry',
    shortDesc: 'Learn how sound and meaning can combine to bring your music to life.',
    styles: STYLES,
    subcategories: [
      { id: 'songwriting', title: 'Songwriting' },
      { id: 'poetic-phrasing', title: 'Poetic Phrasing' },
    ],
  },
  {
    id: 'music',
    title: 'Musical Fluency',
    filterTitle: 'Musical Fluency',
    shortDesc: "Understand and respond to musical thoughts like you're speaking a language.",
    styles: STYLES,
    subcategories: [
      { id: 'ear-training', title: 'Ear Training' },
      { id: 'raaga-music', title: 'Raaga Music' },
      { id: 'harmony', title: 'Harmony' },
      { id: 'composition', title: 'Composition' },
      { id: 'improvisation', title: 'Improvisation' },
      { id: 'read-music', title: 'Read Music' },
      { id: 'transcribe-music', title: 'Transcribe Music' },
    ],
  },
];
