import {
  NOTE_FREQS,
  SA_FREQ,
  LOW_SA_FREQ,
  HIGH_SA_FREQ,
  PA_FREQ,
  LOW_PA_FREQ,
  DHA_FREQ,
  LOW_DHA_FREQ,
  GA_FREQ,
  MA_FREQ,
  RE_FREQ,
  LOW_NI_FREQ,
  NI_FREQ,
  formatNoteList,
} from './notes';

function makeDroneScaleLevel(id, notes) {
  const laneLabels = [...notes].reverse();

  return {
    id,
    title: `Level ${id}`,
    interval: notes.join(' '),
    cueType: 'single-note',
    zoneCount: laneLabels.length,
    laneLabels,
    cueByLane: Object.fromEntries(laneLabels.map((note, lane) => [lane, NOTE_FREQS[note]])),
    helpText: `The drone holds Sa. Hear whether the cue is ${formatNoteList(laneLabels)}.`,
    description: 'Stage 3 scale level.',
  };
}

export const LEVELS = [
  {
    id: 1,
    title: 'Level 1',
    interval: 'Octave',
    cueType: 'slide',
    ratio: 2,
    description: 'Wide pitch slides.',
  },
  {
    id: 2,
    title: 'Level 2',
    interval: 'Fifth',
    cueType: 'slide',
    ratio: 1.5,
    description: 'Smaller pitch slides.',
  },
  {
    id: 3,
    title: 'Level 3',
    interval: 'Two notes',
    cueType: 'two-note',
    lowFreq: SA_FREQ,
    highFreq: HIGH_SA_FREQ,
    description: 'Compare two Sa notes.',
  },
  {
    id: 4,
    title: 'Level 4',
    interval: 'From Sa',
    cueType: 'anchored-two-note',
    lowFreq: LOW_SA_FREQ,
    baseFreq: SA_FREQ,
    highFreq: HIGH_SA_FREQ,
    description: 'Hear whether Sa moves up or down.',
  },
  {
    id: 5,
    title: 'Level 5',
    interval: 'Sa to Pa',
    cueType: 'anchored-two-note',
    lowFreq: LOW_PA_FREQ,
    baseFreq: SA_FREQ,
    highFreq: PA_FREQ,
    description: 'Hear whether Pa is above or below Sa.',
  },
  {
    id: 6,
    title: 'Level 6',
    interval: 'Sa or Pa',
    cueType: 'anchored-two-note',
    lowFreq: SA_FREQ,
    baseFreq: SA_FREQ,
    highFreq: PA_FREQ,
    description: 'Low cue repeats Sa. High cue moves to Pa.',
  },
  {
    id: 7,
    title: 'Level 7',
    interval: 'Three zones',
    cueType: 'sequence',
    zoneCount: 3,
    cueByLane: {
      0: [SA_FREQ, PA_FREQ],
      1: [SA_FREQ, SA_FREQ],
      2: [SA_FREQ, LOW_PA_FREQ],
    },
    description: 'Top, middle, and bottom safe zones.',
  },
  {
    id: 8,
    title: 'Level 8',
    interval: 'Dha or Ga',
    cueType: 'sequence',
    zoneCount: 3,
    cueByLane: {
      0: [SA_FREQ, GA_FREQ],
      1: [SA_FREQ, SA_FREQ],
      2: [SA_FREQ, LOW_DHA_FREQ],
    },
    description: 'Low Dha, repeated Sa, or Ga.',
  },
  {
    id: 9,
    title: 'Level 9',
    interval: 'Ni or Re',
    cueType: 'sequence',
    zoneCount: 3,
    cueByLane: {
      0: [SA_FREQ, RE_FREQ],
      1: [SA_FREQ, SA_FREQ],
      2: [SA_FREQ, LOW_NI_FREQ],
    },
    description: 'Low Ni, repeated Sa, or Re.',
  },
  {
    id: 10,
    title: 'Level 10',
    interval: 'Sa Pa Sa',
    cueType: 'sequence',
    zoneCount: 3,
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, PA_FREQ],
      2: [SA_FREQ, SA_FREQ],
    },
    description: 'Repeated Sa, Pa, or high Sa.',
  },
  {
    id: 11,
    title: 'Level 11',
    interval: 'Sa Ga Pa',
    cueType: 'sequence',
    zoneCount: 3,
    laneLabels: ['Pa', 'Ga', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, PA_FREQ],
      1: [SA_FREQ, GA_FREQ],
      2: [SA_FREQ, SA_FREQ],
    },
    description: 'Repeated Sa, Ga, or Pa.',
  },
  {
    id: 12,
    title: 'Level 12',
    interval: 'Sa Re Ga',
    cueType: 'sequence',
    zoneCount: 3,
    laneLabels: ['Ga', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, GA_FREQ],
      1: [SA_FREQ, RE_FREQ],
      2: [SA_FREQ, SA_FREQ],
    },
    description: 'Repeated Sa, Re, or Ga.',
  },
  {
    id: 13,
    title: 'Level 13',
    interval: "Sa Ga Pa Sa'",
    cueType: 'sequence',
    zoneCount: 4,
    laneLabels: ["Sa'", 'Pa', 'Ga', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, PA_FREQ],
      2: [SA_FREQ, GA_FREQ],
      3: [SA_FREQ, SA_FREQ],
    },
    helpText: "Sa-Sa means bottom. Sa-Ga, Sa-Pa, and Sa-Sa' move upward through the higher zones.",
    description: "Four zones from Sa to high Sa.",
  },
  {
    id: 14,
    title: 'Level 14',
    interval: "Sa Re Dha Sa'",
    cueType: 'sequence',
    zoneCount: 4,
    laneLabels: ["Sa'", 'Dha', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, DHA_FREQ],
      2: [SA_FREQ, RE_FREQ],
      3: [SA_FREQ, SA_FREQ],
    },
    helpText: "Sa-Sa means bottom. Sa-Re, Sa-Dha, and Sa-Sa' move upward through the higher zones.",
    description: "Four zones from Sa to high Sa.",
  },
  {
    id: 15,
    title: 'Level 15',
    interval: 'Sa Re Ga Pa',
    cueType: 'sequence',
    zoneCount: 4,
    laneLabels: ['Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, PA_FREQ],
      1: [SA_FREQ, GA_FREQ],
      2: [SA_FREQ, RE_FREQ],
      3: [SA_FREQ, SA_FREQ],
    },
    helpText: 'Sa-Sa means bottom. Sa-Re, Sa-Ga, and Sa-Pa move upward through the higher zones.',
    description: 'Four zones from Sa to Pa.',
  },
  {
    id: 16,
    title: 'Level 16',
    interval: "Sa Ga Pa Dha Sa'",
    cueType: 'sequence',
    zoneCount: 5,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'Ga', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, DHA_FREQ],
      2: [SA_FREQ, PA_FREQ],
      3: [SA_FREQ, GA_FREQ],
      4: [SA_FREQ, SA_FREQ],
    },
    helpText: "Sa-Sa means bottom. Sa-Ga, Sa-Pa, Sa-Dha, and Sa-Sa' move upward through the higher zones.",
    description: "Five zones from Sa to high Sa.",
  },
  {
    id: 17,
    title: 'Level 17',
    interval: "Sa Re Pa Dha Sa'",
    cueType: 'sequence',
    zoneCount: 5,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, DHA_FREQ],
      2: [SA_FREQ, PA_FREQ],
      3: [SA_FREQ, RE_FREQ],
      4: [SA_FREQ, SA_FREQ],
    },
    helpText: "Sa-Sa means bottom. Sa-Re, Sa-Pa, Sa-Dha, and Sa-Sa' move upward through the higher zones.",
    description: "Five zones from Sa to high Sa.",
  },
  {
    id: 18,
    title: 'Level 18',
    interval: "Sa Re Ga Dha Sa'",
    cueType: 'sequence',
    zoneCount: 5,
    laneLabels: ["Sa'", 'Dha', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, DHA_FREQ],
      2: [SA_FREQ, GA_FREQ],
      3: [SA_FREQ, RE_FREQ],
      4: [SA_FREQ, SA_FREQ],
    },
    helpText: "Sa-Sa means bottom. Sa-Re, Sa-Ga, Sa-Dha, and Sa-Sa' move upward through the higher zones.",
    description: "Five zones from Sa to high Sa.",
  },
  {
    id: 19,
    title: 'Level 19',
    interval: 'Sa Re Ga Pa Dha',
    cueType: 'sequence',
    zoneCount: 5,
    laneLabels: ['Dha', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, DHA_FREQ],
      1: [SA_FREQ, PA_FREQ],
      2: [SA_FREQ, GA_FREQ],
      3: [SA_FREQ, RE_FREQ],
      4: [SA_FREQ, SA_FREQ],
    },
    helpText: 'Sa-Sa means bottom. Sa-Re, Sa-Ga, Sa-Pa, and Sa-Dha move upward through the higher zones.',
    description: 'Five zones from Sa to Dha.',
  },
  {
    id: 20,
    title: 'Level 20',
    interval: "Sa Re Ga Pa Dha Sa'",
    cueType: 'sequence',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: [SA_FREQ, HIGH_SA_FREQ],
      1: [SA_FREQ, DHA_FREQ],
      2: [SA_FREQ, PA_FREQ],
      3: [SA_FREQ, GA_FREQ],
      4: [SA_FREQ, RE_FREQ],
      5: [SA_FREQ, SA_FREQ],
    },
    helpText: "Sa-Sa means bottom. Sa-Re, Sa-Ga, Sa-Pa, Sa-Dha, and Sa-Sa' move upward through the higher zones.",
    description: "Six zones from Sa to high Sa.",
  },
  {
    id: 21,
    title: 'Level 21',
    interval: 'Sa Pa',
    cueType: 'single-note',
    zoneCount: 2,
    laneLabels: ['Pa', 'Sa'],
    cueByLane: {
      0: PA_FREQ,
      1: SA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Sa or Pa.',
    description: 'Single-note cues over a Sa-Pa drone.',
  },
  {
    id: 22,
    title: 'Level 22',
    interval: 'Pa Sa low Pa',
    cueType: 'single-note',
    zoneCount: 3,
    laneLabels: ['Pa', 'Sa', 'low Pa'],
    cueByLane: {
      0: PA_FREQ,
      1: SA_FREQ,
      2: LOW_PA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Pa, Sa, or low Pa.',
    description: 'Single-note version of Level 7.',
  },
  {
    id: 23,
    title: 'Level 23',
    interval: 'Ga Sa low Dha',
    cueType: 'single-note',
    zoneCount: 3,
    laneLabels: ['Ga', 'Sa', 'low Dha'],
    cueByLane: {
      0: GA_FREQ,
      1: SA_FREQ,
      2: LOW_DHA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Ga, Sa, or low Dha.',
    description: 'Single-note version of Level 8.',
  },
  {
    id: 24,
    title: 'Level 24',
    interval: 'Re Sa low Ni',
    cueType: 'single-note',
    zoneCount: 3,
    laneLabels: ['Re', 'Sa', 'low Ni'],
    cueByLane: {
      0: RE_FREQ,
      1: SA_FREQ,
      2: LOW_NI_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Re, Sa, or low Ni.',
    description: 'Single-note version of Level 9.',
  },
  {
    id: 25,
    title: 'Level 25',
    interval: "Sa' Pa Sa",
    cueType: 'single-note',
    zoneCount: 3,
    laneLabels: ["Sa'", 'Pa', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: PA_FREQ,
      2: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Pa, or Sa.",
    description: 'Single-note version of Level 10.',
  },
  {
    id: 26,
    title: 'Level 26',
    interval: 'Pa Ga Sa',
    cueType: 'single-note',
    zoneCount: 3,
    laneLabels: ['Pa', 'Ga', 'Sa'],
    cueByLane: {
      0: PA_FREQ,
      1: GA_FREQ,
      2: SA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Pa, Ga, or Sa.',
    description: 'Single-note version of Level 11.',
  },
  {
    id: 27,
    title: 'Level 27',
    interval: 'Ga Re Sa',
    cueType: 'single-note',
    zoneCount: 3,
    laneLabels: ['Ga', 'Re', 'Sa'],
    cueByLane: {
      0: GA_FREQ,
      1: RE_FREQ,
      2: SA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Ga, Re, or Sa.',
    description: 'Single-note version of Level 12.',
  },
  {
    id: 28,
    title: 'Level 28',
    interval: "Sa' Pa Ga Sa",
    cueType: 'single-note',
    zoneCount: 4,
    laneLabels: ["Sa'", 'Pa', 'Ga', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: PA_FREQ,
      2: GA_FREQ,
      3: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Pa, Ga, or Sa.",
    description: 'Single-note version of Level 13.',
  },
  {
    id: 29,
    title: 'Level 29',
    interval: "Sa' Dha Re Sa",
    cueType: 'single-note',
    zoneCount: 4,
    laneLabels: ["Sa'", 'Dha', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: RE_FREQ,
      3: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Re, or Sa.",
    description: 'Single-note version of Level 14.',
  },
  {
    id: 30,
    title: 'Level 30',
    interval: 'Pa Ga Re Sa',
    cueType: 'single-note',
    zoneCount: 4,
    laneLabels: ['Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: PA_FREQ,
      1: GA_FREQ,
      2: RE_FREQ,
      3: SA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Pa, Ga, Re, or Sa.',
    description: 'Single-note version of Level 15.',
  },
  {
    id: 31,
    title: 'Level 31',
    interval: "Sa' Dha Pa Ga Sa",
    cueType: 'single-note',
    zoneCount: 5,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'Ga', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: PA_FREQ,
      3: GA_FREQ,
      4: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Pa, Ga, or Sa.",
    description: 'Single-note version of Level 16.',
  },
  {
    id: 32,
    title: 'Level 32',
    interval: "Sa' Dha Pa Re Sa",
    cueType: 'single-note',
    zoneCount: 5,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: PA_FREQ,
      3: RE_FREQ,
      4: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Pa, Re, or Sa.",
    description: 'Single-note version of Level 17.',
  },
  {
    id: 33,
    title: 'Level 33',
    interval: "Sa' Dha Ga Re Sa",
    cueType: 'single-note',
    zoneCount: 5,
    laneLabels: ["Sa'", 'Dha', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: GA_FREQ,
      3: RE_FREQ,
      4: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Ga, Re, or Sa.",
    description: 'Single-note version of Level 18.',
  },
  {
    id: 34,
    title: 'Level 34',
    interval: 'Dha Pa Ga Re Sa',
    cueType: 'single-note',
    zoneCount: 5,
    laneLabels: ['Dha', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: DHA_FREQ,
      1: PA_FREQ,
      2: GA_FREQ,
      3: RE_FREQ,
      4: SA_FREQ,
    },
    helpText: 'The drone holds Sa. Hear whether the cue is Dha, Pa, Ga, Re, or Sa.',
    description: 'Single-note version of Level 19.',
  },
  {
    id: 35,
    title: 'Level 35',
    interval: "Sa' Dha Pa Ga Re Sa",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: PA_FREQ,
      3: GA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Pa, Ga, Re, or Sa.",
    description: 'Single-note version of Level 20.',
  },
  {
    id: 36,
    title: 'Level 36',
    interval: "Sa Re ma Pa Dha Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'ma', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: PA_FREQ,
      3: MA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Pa, ma, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 37,
    title: 'Level 37',
    interval: "Sa Re Ga ma Dha Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Dha', 'ma', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: MA_FREQ,
      3: GA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, ma, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 38,
    title: 'Level 38',
    interval: "Sa Re Ga ma Pa Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Pa', 'ma', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: PA_FREQ,
      2: MA_FREQ,
      3: GA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Pa, ma, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 39,
    title: 'Level 39',
    interval: "Sa Ga ma Pa Dha Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'ma', 'Ga', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: PA_FREQ,
      3: MA_FREQ,
      4: GA_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Pa, ma, Ga, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 40,
    title: 'Level 40',
    interval: "Sa Re Ga ma Pa Dha Sa'",
    cueType: 'single-note',
    zoneCount: 7,
    laneLabels: ["Sa'", 'Dha', 'Pa', 'ma', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: DHA_FREQ,
      2: PA_FREQ,
      3: MA_FREQ,
      4: GA_FREQ,
      5: RE_FREQ,
      6: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Dha, Pa, ma, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 41,
    title: 'Level 41',
    interval: "Sa Re Ga Pa Ni Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Ni', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: PA_FREQ,
      3: GA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Pa, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 42,
    title: 'Level 42',
    interval: "Sa Re ma Pa Ni Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Ni', 'Pa', 'ma', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: PA_FREQ,
      3: MA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Pa, ma, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 43,
    title: 'Level 43',
    interval: "Sa Re ma Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'ma', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: MA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, ma, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 44,
    title: 'Level 44',
    interval: "Sa Ga ma Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'ma', 'Ga', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: MA_FREQ,
      4: GA_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, ma, Ga, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 45,
    title: 'Level 45',
    interval: "Sa Re Ga Pa Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 7,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: PA_FREQ,
      4: GA_FREQ,
      5: RE_FREQ,
      6: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, Pa, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 46,
    title: 'Level 46',
    interval: "Sa Re Ga Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 6,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: GA_FREQ,
      4: RE_FREQ,
      5: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 47,
    title: 'Level 47',
    interval: "Sa Re Ga ma Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 7,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'ma', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: MA_FREQ,
      4: GA_FREQ,
      5: RE_FREQ,
      6: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, ma, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 48,
    title: 'Level 48',
    interval: "Sa Re Ga Pa Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 7,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'Pa', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: PA_FREQ,
      4: GA_FREQ,
      5: RE_FREQ,
      6: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, Pa, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 49,
    title: 'Level 49',
    interval: "Sa Re ma Pa Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 7,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'Pa', 'ma', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: PA_FREQ,
      4: MA_FREQ,
      5: RE_FREQ,
      6: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, Pa, ma, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  {
    id: 50,
    title: 'Level 50',
    interval: "Sa Re Ga ma Pa Dha Ni Sa'",
    cueType: 'single-note',
    zoneCount: 8,
    laneLabels: ["Sa'", 'Ni', 'Dha', 'Pa', 'ma', 'Ga', 'Re', 'Sa'],
    cueByLane: {
      0: HIGH_SA_FREQ,
      1: NI_FREQ,
      2: DHA_FREQ,
      3: PA_FREQ,
      4: MA_FREQ,
      5: GA_FREQ,
      6: RE_FREQ,
      7: SA_FREQ,
    },
    helpText: "The drone holds Sa. Hear whether the cue is high Sa, Ni, Dha, Pa, ma, Ga, Re, or Sa.",
    description: 'Drone-style single-note level.',
  },
  ...[
    [51, ['Sa', 'ga', 'ma', 'dha', 'Ni', "Sa'"]],
    [52, ['Sa', 'Ga', 'ma', 'Pa', 'Ni', "Sa'"]],
    [53, ['Sa', 'Re', 'ga', 'Pa', 'Dha', "Sa'"]],
    [54, ['Sa', 're', 'ga', 'Pa', 'dha', "Sa'"]],
    [55, ['Sa', 're', 'ma', 'Pa', 'dha', "Sa'"]],
    [56, ['Sa', 'ga', 'ma', 'Pa', 'ni', "Sa'"]],
    [57, ['Sa', 'Ga', 'Pa', 'Dha', 'ni', "Sa'"]],
    [58, ['Sa', 're', 'Ga', 'Pa', 'dha', "Sa'"]],
    [59, ['Sa', 'Re', 'Ma', 'Pa', 'Dha', 'ni', "Sa'"]],
    [60, ['Sa', 'Re', 'Ga', 'ma', 'Pa', 'Dha', 'ni', "Sa'"]],
    [61, ['Sa', 'Re', 'ga', 'ma', 'Pa', 'Dha', 'ni', "Sa'"]],
    [62, ['Sa', 'Re', 'ga', 'ma', 'Pa', 'dha', 'ni', "Sa'"]],
    [63, ['Sa', 're', 'ga', 'ma', 'Pa', 'dha', 'ni', "Sa'"]],
    [64, ['Sa', 'Re', 'Ga', 'Ma', 'Pa', 'Dha', 'Ni', "Sa'"]],
    [65, ['Sa', 're', 'Ga', 'Ma', 'Pa', 'dha', 'Ni', "Sa'"]],
    [66, ['Sa', 're', 'ga', 'Ma', 'Pa', 'dha', 'Ni', "Sa'"]],
    [67, ['Sa', 're', 'Ga', 'ma', 'Pa', 'dha', 'Ni', "Sa'"]],
    [68, ['Sa', 're', 'Ga', 'ma', 'Pa', 'Dha', 'ni', "Sa'"]],
    [69, ['Sa', 're', 'Ga', 'Ma', 'Pa', 'dha', 'ni', "Sa'"]],
    [70, ['Sa', 'Re', 'Ga', 'ma', 'Pa', 'dha', 'ni', "Sa'"]],
    [71, ['Sa', 'Re', 'Ga', 'ma', 'Pa', 'dha', 'Ni', "Sa'"]],
    [72, ['Sa', 'Re', 'ga', 'Ma', 'Pa', 'dha', 'Ni', "Sa'"]],
    [73, ['Sa', 're', 'Ga', 'ma', 'Pa', 'dha', 'ni', "Sa'"]],
    [74, ['Sa', 're', 'ga', 'ma', 'Pa', 'Dha', 'Ni', "Sa'"]],
    [75, ['Sa', 'Re', 'Ga', 'ma', 'Pa', 'dha', 'ni', "Sa'"]],
  ].map(([id, notes]) => makeDroneScaleLevel(id, notes)),
];
